# .travis.yml
language: shell
os: windows
install:
  - choco install unity
cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE
jobs:
  include:
    - stage: build
      script: 
      - powershell
      - build.bat
    - stage: test
      script: powershell test.bat
